### ISSUE TITLE
Example of usage as regular LSTM?

### ISSUE THREAD

**Issue by slerman12** [daehwannam/pytorch-rnn-util#1]
How would it look like to call a regular LSTM with this code? That would help me understand it better.

**Comment by daehwannam** [comment]
I updated [example.py](https://github.com/daehwannam/pytorch-rnn-util/blob/master/example.py). Please check the example.
You can replace instances of LSTMFrame or LayerNormLSTM with those of regular ones by uncommenting the lines with torch.nn.LSTM.
