### ISSUE TITLE
LSTMFrame batch_first unused?

### ISSUE THREAD

**Issue by mzietlow** [daehwannam/pytorch-rnn-util#2]
Thank you for your work! However, could you please elaborate on the batch_first option in LSTMFrame?

1.) it is unused in the code and 2.) feeding an actual batch first tensor with leads to an exception, because the batch is treated as if it were the sequence (dimension mismatch within the cell). Could you provide a minimal working example or similar reference on how to use LSTMFrame with batch-first data?

Best wishes
~

**Comment by daehwannam** [comment]
As you said, the batch_first option is not implemented yet, so I'm gonna add the feature sooner or later. However, if you want to process batch first tensors with the current `LSTMFrame`, there are several options:

- Processing a batch first tensor with `pack_padded_sequence` and `pad_packed_sequence` before and after the tensor passes through `LSTMFrame.forward`, where the two functions' arguments should include `batch_first=True`.
- Or using `.transpose` function of the batch first tensor to swap dimensions of sequence and batch indices.

**Comment by daehwannam** [comment]
The following link has a helpful example: https://gist.github.com/Tushar-N/dfca335e370a2bc3bc79876e6270099e

**Comment by daehwannam** [comment]
I added `batch_first` feature and [example.py](https://github.com/daehwannam/pytorch-rnn-util/blob/master/example.py) include a snippet using the option.

**Comment by mzietlow** [comment]
Wow, thank you for your efforts, that is really helpful! I'll close this accordingly
